import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SettingsMenu from '@/components/SettingsMenu/SettingsMenu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="h-16 border-b-white/20 border-b flex flex-row justify-between items-center mx-6">
          <h1>cool bank</h1>
          <SettingsMenu />
        </nav>
        {children}
      </body>
    </html>
  );
}
