import './globals.css';

import type { Metadata } from 'next';
import { Inter, Red_Hat_Display } from 'next/font/google';

import Nav from '@/components/Nav/Nav';
import { AppProvider } from '@/context/AppProvider';

const inter = Inter({ subsets: ['latin'] });
const redHatDisplay = Red_Hat_Display({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const mode = 'dark';

  return (
    <html lang="en">
      <AppProvider>
        <body
          className={`${inter.className} ${mode} h-screen overflow-x-hidden bg-gradient-to-b from-stone-800 to-stone-900`}
        >
          <Nav />
            {children}
        </body>
      </AppProvider>
    </html>
  );
}
